# render.yaml
services:
  - type: web
    name: daily-performance-manager
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: EMAIL_USERNAME
        fromEnvVar: EMAIL_USERNAME
      - key: EMAIL_PASSWORD
        fromEnvVar: EMAIL_PASSWORD
      - key: HUBSPOT_TOKEN
        fromEnvVar: HUBSPOT_TOKEN
